### ISSUE TITLE
YouTube Download Requests fail on own instance

### ISSUE THREAD

**Issue by w2ppx** [imputnet/cobalt#496]
**bug description**
when downloading from youtube, it returns an error from youtube.js library, tried to change ip, didnt help

**reproduction steps**
steps to reproduce the behavior:
3. download this video: **[[link here]](https://www.youtube.com/watch?v=kkg_7cssV7Q)** 
4. see error

**screenshots**
![firefox_LiXNb0k3Sa](https://github.com/imputnet/cobalt/assets/98914858/7dcd1051-0145-40c6-91eb-2b313e46a132)

**links**
happens with any link, my instance: web.eepy.today

**platform**
- OS [windows]
- browser [firefox]
- version [124]

**additional context**
the error:
```
TypeError: Failed to parse URL from [object Request]
    at fetch (/root/cobalt/api/node_modules/undici/index.js:111:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:405:5)
      at new URL (node:internal/url:676:13)
      at new Request (/root/cobalt/api/node_modules/undici/lib/web/fetch/request.js:117:21)
      at fetch (/root/cobalt/api/node_modules/undici/lib/web/fetch/index.js:136:21)
      at fetch (/root/cobalt/api/node_modules/undici/index.js:108:18)
      at HTTPClient.<anonymous> (file:///root/cobalt/api/src/modules/processing/services/youtube.js:44:26)
      at HTTPClient.<anonymous> (file:///root/cobalt/api/node_modules/youtubei.js/dist/src/utils/HTTPClient.js:106:89)
      at Generator.next (<anonymous>)
      at /root/cobalt/api/node_modules/tslib/tslib.js:169:75
      at new Promise (<anonymous>) {
    input: '[object Request]',
    code: 'ERR_INVALID_URL'
  }
}
```
my instance is using last version:
```
cobalt API v.7.13.3-5c9ecb2 (current)
Start time: Wed, 15 May 2024 20:53:29 GMT (1715806409815)
```

**Comment by dumbmoron** [comment]
hi, are you using the pre-built docker image, or are you building your own image, or are you running cobalt standalone (without any containerization)?

**Comment by wukko** [comment]
have you edited the source code in any way?

**Comment by w2ppx** [comment]
> hi, are you using the pre-built docker image, or are you building your own image, or are you running cobalt standalone (without any containerization)?

i am using cobalt standalone



> have you edited the source code in any way?

no, i didn’t modify it

**Comment by wukko** [comment]
@w2ppx can you run `npm install`? it should fix the issue

**Comment by w2ppx** [comment]
> @w2ppx can you run `npm install`? it should fix the issue

thanks, it worked!

**Comment by wukko** [comment]
no problem :D
