### ISSUE TITLE
How do i deploy this on Shared Hosting?

### ISSUE THREAD

**Issue by oksurya** [imputnet/cobalt#640]
im running nemecheap shared hosting its supports nodejs.

![image](https://github.com/user-attachments/assets/3332156f-0646-4397-b43f-c8b4375be306)

error: 

returncode: 1
stdout:
> cobalt@7.14.6 start
> node src/cobalt
stderr:
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: git rev-parse --short HEAD
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:889:11)
    at execSync (node:child_process:961:15)
    at shortCommit (file:///home/proxzdwl/igapi.oksurya.com/src/modules/sub/currentCommit.js:7:13)
    at file:///home/proxzdwl/igapi.oksurya.com/src/cobalt.js:16:19
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:474:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:119:5) {
  status: 128,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(143) [Uint8Array] [
      102,  97, 116,  97, 108,  58,  32, 110, 111, 116,  32,  97,
       32, 103, 105, 116,  32, 114, 101, 112, 111, 115, 105, 116,
      111, 114, 121,  32,  40, 111, 114,  32,  97, 110, 121,  32,
      112,  97, 114, 101, 110, 116,  32, 117, 112,  32, 116, 111,
       32, 109, 111, 117, 110, 116,  32, 112, 111, 105, 110, 116,
       32,  47, 104, 111, 109, 101,  41,  10,  83, 116, 111, 112,
      112, 105, 110, 103,  32,  97, 116,  32, 102, 105, 108, 101,
      115, 121, 115, 116, 101, 109,  32,  98, 111, 117, 110, 100,
       97, 114, 121,  32,
      ... 43 more items
    ]
  ],
  pid: 3908270,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(143) [Uint8Array] [
    102,  97, 116,  97, 108,  58,  32, 110, 111, 116,  32,  97,
     32, 103, 105, 116,  32, 114, 101, 112, 111, 115, 105, 116,
    111, 114, 121,  32,  40, 111, 114,  32,  97, 110, 121,  32,
    112,  97, 114, 101, 110, 116,  32, 117, 112,  32, 116, 111,
     32, 109, 111, 117, 110, 116,  32, 112, 111, 105, 110, 116,
     32,  47, 104, 111, 109, 101,  41,  10,  83, 116, 111, 112,
    112, 105, 110, 103,  32,  97, 116,  32, 102, 105, 108, 101,
    115, 121, 115, 116, 101, 109,  32,  98, 111, 117, 110, 100,
     97, 114, 121,  32,
    ... 43 more items
  ]
}

Node.js v22.1.0

**Comment by wukko** [comment]
the error here implies that git is needed to get branch info. i recommend hosting the docker image (and preferably somewhere else that is not as dated).
