### ISSUE TITLE
@imput/version-info Unable to install

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [imputnet/cobalt#773]
### problem description

@imput/version-info Unable to install

### your instance configuration

```shell
[2Kxiazai  |  ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@imput/version-info@workspace:^" is in the dependencies but no package named "@imput/version-info" is present in the workspace
[2Kxiazai  | 
[2Kxiazai  | This error happened while installing a direct dependency of /app
[2Kxiazai  | 
[2Kxiazai  | Packages found in the workspace: 
[2Kxiazai  | 
[2Kxiazai  | > @imput/cobalt-web@10.0.0 build /app
[2Kxiazai  | > vite build
[2Kxiazai  | 
[2Kxiazai  | vite v5.4.7 building SSR bundle for production...
[2Kxiazai  | transforming...
[2Kxiazai  | ✓ 85 modules transformed.
[2Kxiazai  | x Build failed in 1.08s
[2Kxiazai  | error during build:
[2Kxiazai  | [vite]: Rollup failed to resolve import "@imput/version-info" from "/app/src/routes/version.json/+server.ts".
[2Kxiazai  | This is most likely unintended because it can break your application at runtime.
[2Kxiazai  | If you do want to externalize this module explicitly add it to
[2Kxiazai  | `build.rollupOptions.external`
[2Kxiazai  |     at viteWarn (file:///app/node_modules/.pnpm/vite@5.4.7_@types+node@20.16.5/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:65531:17)
[2Kxiazai  |     at onRollupWarning (file:///app/node_modules/.pnpm/vite@5.4.7_@types+node@20.16.5/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:65563:5)
[2Kxiazai  |     at onwarn (file:///app/node_modules/.pnpm/vite@5.4.7_@types+node@20.16.5/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:65226:7)
[2Kxiazai  |     at file:///app/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:18686:13
[2Kxiazai  |     at Object.logger [as onLog] (file:///app/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:20325:9)
[2Kxiazai  |     at ModuleLoader.handleInvalidResolvedId (file:///app/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:19275:26)
[2Kxiazai  |     at file:///app/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:19233:26
[2Kxiazai  |  ELIFECYCLE  Command failed with exit code 1.
xiazai exited with code 0
```

**Comment by lostdusty** [comment]
unable to install what

**Comment by wukko** [comment]
why did you remove the packages folder? do installation instructions tell you to do so?
